// text.h — bitmap font: text strings expressed as instanced glyph quads.
//
// This is the whole point of the instanced-rendering design: text is NOT a
// special renderer feature. makeText is a pure function that turns a string
// into a vector<Instance> — one non-billboard quad per character, laid out
// along +X, each sampling a cell of the font sheet (art/font.png, generated by
// scripts/gen_font.py). The renderer never learns what "text" is.
//
// Font sheet layout (scripts/gen_font.py): 16 cols x 6 rows of square cells,
// covering ASCII 32 ("space") through 127 in row-major order — cell index =
// ascii - 32, same flat-index convention as every other sprite sheet in the
// game (art/penguin.png, art/tiles.png).
#pragma once

#include <string>
#include <vector>

#include "instance.h"

namespace cv {

constexpr int FONT_FIRST_ASCII = 32;                          // ' '
constexpr int FONT_LAST_ASCII  = 127;                          // inclusive
constexpr int FONT_NUM_GLYPHS  = FONT_LAST_ASCII - FONT_FIRST_ASCII + 1;  // 96 (16x6)

// Build one non-billboard quad per character of `s`, positioned left-to-right
// along +X starting at `pos` (each glyph's own origin advances by `charW`, so
// the whole string spans s.size() * charW world units). `charH` is the quad
// height. `fontSheet` is the sheet index (see Scene::sheets / entity "sheet")
// carrying a font layout; `tint` is the RGBA multiplier (alpha < 1 for a
// translucent title fade, etc).
//
// Bytes outside the covered ASCII range render as the blank "space" cell
// (frame 0) rather than an arbitrary wrong glyph, so stray bytes are silent,
// not glitchy. Pure function: touches no engine/game state.
std::vector<Instance> makeText(const std::string& s, Vec3 pos,
                                float charW, float charH,
                                int fontSheet, Vec4 tint);

} // namespace cv
